input {
  beats {
    port => 5044
  }
  gelf {
    port => 5000
  }
}

filter {
  json {
    source => "message"
    target => "log_data"
    skip_on_invalid_json => true
  }

  mutate {
    add_field => { "environment" => "production" }
    rename => { "host" => "[host][name]" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    ilm_enabled => true
    ilm_rollover_alias => "docker-logs"
    ilm_policy => "7-days-default"
  }
}
